[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
gas_report = ["*"]

[fmt]
line_lengty = 80
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
