[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.26"
optimizer = true
gas_reports = ["*"]
gas_reports_ignore = ["MyToken"]

[fmt]
line_lengty = 80
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"

[profile.perftest]
test = "test-performance"
verbosity = 2
gas_limit = 320000000 # u64::MAX

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
